apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ template "mongodb.name" . }}
    chart: {{ template "mongodb.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "mongodb.fullname" . }}
data:
    mongodbUsername: {{ .Values.mongodbUsername }}
    mongodbDatabase: {{ .Values.mongodbDatabase }}
