apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ include "alterego.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "alterego.name" . }}
    helm.sh/chart: {{ include "alterego.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  schedule: "10 * * * *"
  jobTemplate:
    spec:
      replicas: {{ .Values.replicaCount }}
      selector:
        matchLabels:
          app.kubernetes.io/name: {{ include "alterego.name" . }}
          app.kubernetes.io/instance: {{ .Release.Name }}
      template:
        metadata:
          labels:
            app.kubernetes.io/name: {{ include "alterego.name" . }}
            app.kubernetes.io/instance: {{ .Release.Name }}
        spec:
          containers:
            - name: {{ .Chart.Name }}
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              env:
              - name: SLACK_API_TOKEN
                value: {{ .Values.SlackAuth }}
              - name: MONGODB_USERNAME
                valueFrom:
                  configMapKeyRef:
                    name: mongodb
                    key: mongodbUsername
              - name: MONGODB_DATABASE
                valueFrom:
                  configMapKeyRef:
                    name: mongodb
                    key: mongodbDatabase
              - name: MONGODB_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: mongodb
                    key: mongodb-password
              ports:
                - name: http
                  containerPort: 80
                  protocol: TCP
              resources:
                {{- toYaml .Values.resources | nindent 12 }}
            restartPolicy: OnFailure
